name:                esa-ol
version:             0.1.0.0
github:              "adamrk/esa-ol"
license:             BSD3
author:              "Adam Bratschi-Kaye"
maintainer:          "ark.email@gmail.com"
copyright:           "All Rights Reserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            project

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/adamrk/esa-ol#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  esa-ol-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esa-ol

tests:
  esa-ol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esa-ol
